wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1711897962.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.13
      5: 0.16.5
      6: 4.39.2
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
